<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BahanBaku;
use App\Models\Product;
use App\Models\Bom;
use App\Models\Category;
use App\Models\Unit;
use Illuminate\Support\Str;

class CeramicDataSeeder extends Seeder
{
    public function run()
    {
        $category = Category::firstOrCreate(['name' => 'General', 'slug' => 'general']);
        
        $unitPcs = Unit::firstOrCreate(['name' => 'Pcs'], ['symbol' => 'pcs']);
        $unitKg = Unit::firstOrCreate(['name' => 'Kilogram'], ['symbol' => 'kg']);
        $unitLiter = Unit::firstOrCreate(['name' => 'Liter'], ['symbol' => 'ltr']);

        // 1. Create New Bahan Baku
        $materials = [
            ['sku' => 'BB-C-003', 'name' => 'Tanah Liat Kaolin', 'unit_id' => $unitKg->id, 'purchase_price' => 7500, 'min_stock' => 50, 'qty' => 500],
            ['sku' => 'BB-C-004', 'name' => 'Tanah Liat Stoneware', 'unit_id' => $unitKg->id, 'purchase_price' => 6000, 'min_stock' => 50, 'qty' => 500],
            ['sku' => 'BB-C-005', 'name' => 'Glasir Bening Cair', 'unit_id' => $unitLiter->id, 'purchase_price' => 15000, 'min_stock' => 20, 'qty' => 200],
            ['sku' => 'BB-C-006', 'name' => 'Pewarna Biru Kobalt', 'unit_id' => $unitLiter->id, 'purchase_price' => 25000, 'min_stock' => 10, 'qty' => 100],
        ];

        $bbMap = [];
        foreach ($materials as $m) {
            $bb = BahanBaku::firstOrCreate(
                ['sku' => $m['sku']],
                [
                    'name' => $m['name'],
                    'category_id' => $category->id,
                    'unit_id' => $m['unit_id'],
                    'purchase_price' => $m['purchase_price'],
                    'min_stock' => $m['min_stock'],
                    'quantity' => $m['qty'], // Initial stock
                ]
            );
            $bb->update(['quantity' => $m['qty']]);
            $bbMap[$m['sku']] = $bb->id;
        }

        // Get existing materials just in case
        $tlSuper = BahanBaku::where('name', 'Tanah Liat Super')->first();
        $tlSuperId = $tlSuper ? $tlSuper->id : $bbMap['BB-C-003'];

        // 2. Create New Products
        $products = [
            [
                'sku' => 'PRD-C-MUG', 'name' => 'Gelas Mug Keramik Custom', 'selling_price' => 35000, 'min_stock' => 20, 'qty' => 100,
                'bom' => [
                    ['bahan_baku_id' => $bbMap['BB-C-004'], 'quantity' => 1], // 1 kg Stoneware
                    ['bahan_baku_id' => $bbMap['BB-C-005'], 'quantity' => 0.1], // 0.1 L Glasir Bening
                ]
            ],
            [
                'sku' => 'PRD-C-VAS', 'name' => 'Vas Bunga Keramik Minimalis', 'selling_price' => 85000, 'min_stock' => 10, 'qty' => 50,
                'bom' => [
                    ['bahan_baku_id' => $bbMap['BB-C-003'], 'quantity' => 3], // 3 kg Kaolin
                    ['bahan_baku_id' => $bbMap['BB-C-006'], 'quantity' => 0.2], // 0.2 L Pewarna Biru
                ]
            ],
            [
                'sku' => 'PRD-C-MANGKUK', 'name' => 'Mangkuk Ramen Keramik', 'selling_price' => 45000, 'min_stock' => 30, 'qty' => 150,
                'bom' => [
                    ['bahan_baku_id' => $tlSuperId, 'quantity' => 2], 
                    ['bahan_baku_id' => $bbMap['BB-C-005'], 'quantity' => 0.15],
                ]
            ],
        ];

        foreach ($products as $p) {
            $product = Product::firstOrCreate(
                ['sku' => $p['sku']],
                [
                    'name' => $p['name'],
                    'category_id' => $category->id,
                    'unit_id' => $unitPcs->id,
                    'selling_price' => $p['selling_price'],
                    'purchase_price' => $p['selling_price'] * 0.6, // Estimated COGS
                    'min_stock' => $p['min_stock'],
                    'quantity' => $p['qty'], // Initial stock
                    'is_active' => true,
                ]
            );
            $product->update(['quantity' => $p['qty']]);

            // 3. Create BOM
            $bomName = 'Resep ' . $p['name'];
            $bom = Bom::firstOrCreate(
                ['product_id' => $product->id, 'name' => $bomName],
                ['is_active' => true, 'notes' => 'Generated by Ceramic Seeder']
            );

            // Create BOM Items if empty
            if ($bom->items()->count() == 0) {
                foreach ($p['bom'] as $item) {
                    $bom->items()->create([
                        'bahan_baku_id' => $item['bahan_baku_id'],
                        'quantity' => $item['quantity'],
                    ]);
                }
            }
        }

        echo "Berhasil generate produk keramik dan bahan bakunya!\n";
    }
}
