<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Produksi;
use App\Models\BahanBaku;
use App\Models\Product;
use App\Models\Bom;
use App\Models\User;
use App\Models\Unit;
use App\Models\Category;
use App\Models\DetailProduksi;
use App\Models\HasilProduksi;
use App\Services\StockService;
use App\Enums\AdjustmentType;
use Illuminate\Support\Str;

class DummyTransactionSeeder extends Seeder
{
    public function run()
    {
        // 1. Ensure basic master data exists
        $admin = User::where('role', 'admin')->first() ?? User::factory()->create(['role' => 'admin', 'name' => 'Admin Dummy']);
        $unit = Unit::first() ?? Unit::create(['name' => 'Pcs', 'symbol' => 'pcs']);
        $category = Category::first() ?? Category::create(['name' => 'General']);

        // Create Materials
        $bb1 = BahanBaku::firstOrCreate(['sku' => 'BB-DUMMY-1'], ['name' => 'Tanah Liat Super', 'category_id' => $category->id, 'unit_id' => $unit->id, 'purchase_price' => 5000, 'min_stock' => 10]);
        $bb2 = BahanBaku::firstOrCreate(['sku' => 'BB-DUMMY-2'], ['name' => 'Pewarna Keramik', 'category_id' => $category->id, 'unit_id' => $unit->id, 'purchase_price' => 2000, 'min_stock' => 5]);

        // Inject initial stock directly for smooth testing
        $bb1->update(['quantity' => 1000]);
        $bb2->update(['quantity' => 1000]);

        // Create Product
        $product = Product::firstOrCreate(['sku' => 'PRD-DUMMY-1'], ['name' => 'Piring Keramik Estetik', 'category_id' => $category->id, 'unit_id' => $unit->id, 'selling_price' => 25000, 'purchase_price' => 10000, 'min_stock' => 50]);
        $product->update(['quantity' => 500]);

        // Create BOM
        $bom = Bom::firstOrCreate(['product_id' => $product->id, 'name' => 'Resep Piring Estetik Default'], ['is_active' => true, 'notes' => 'Generated by seeder']);
        if ($bom->items()->count() == 0) {
            $bom->items()->create(['bahan_baku_id' => $bb1->id, 'quantity' => 2]);
            $bom->items()->create(['bahan_baku_id' => $bb2->id, 'quantity' => 1]);
        }

        $stockService = app(StockService::class);

        // ==========================================
        // 1. 10 PRODUKSI BERBEDA
        // ==========================================
        for ($i = 1; $i <= 10; $i++) {
            $status = 'pending'; // Default
            if ($i <= 3) $status = 'completed'; // 3 completed
            else if ($i <= 6) $status = 'in_progress'; // 3 in_progress
            
            $produksi = Produksi::create([
                'production_number' => 'PRD-SEED-' . Str::random(5) . '-' . $i,
                'product_id' => $product->id,
                'bom_id' => $bom->id,
                'target_quantity' => 10 + $i,
                'status' => $status,
                'start_date' => now()->subDays(rand(1, 10)),
                'notes' => "Dummy Produksi #$i",
                'created_by' => $admin->id,
            ]);

            // Request Materials
            foreach ($bom->items as $item) {
                DetailProduksi::create([
                    'produksi_id' => $produksi->id,
                    'bahan_baku_id' => $item->bahan_baku_id,
                    'quantity_requested' => $item->quantity * $produksi->target_quantity,
                    'quantity_approved' => in_array($status, ['in_progress', 'completed']) ? ($item->quantity * $produksi->target_quantity) : 0,
                    'status' => in_array($status, ['in_progress', 'completed']) ? 'approved' : 'pending',
                ]);
            }

            // If completed, generate HasilProduksi
            if ($status === 'completed') {
                HasilProduksi::create([
                    'produksi_id' => $produksi->id,
                    'product_id' => $produksi->product_id,
                    'quantity_produced' => $produksi->target_quantity, // Perfect yield
                    'quantity_defect' => 0,
                    'status' => 'pending_gudang', // Needs gudang approval
                ]);
            }
        }

        // ==========================================
        // 2. 3 PRODUKSI GAGAL (FAILED)
        // ==========================================
        for ($i = 1; $i <= 3; $i++) {
            $produksi = Produksi::create([
                'production_number' => 'PRD-FAIL-' . Str::random(5) . '-' . $i,
                'product_id' => $product->id,
                'bom_id' => $bom->id,
                'target_quantity' => 5 + $i,
                'status' => 'failed',
                'start_date' => now()->subDays(rand(1, 5)),
                'notes' => "Dummy Produksi Gagal #$i",
                'created_by' => $admin->id,
            ]);

            foreach ($bom->items as $item) {
                DetailProduksi::create([
                    'produksi_id' => $produksi->id,
                    'bahan_baku_id' => $item->bahan_baku_id,
                    'quantity_requested' => $item->quantity * $produksi->target_quantity,
                    'status' => 'pending', // Never supplied
                ]);
            }
        }

        // ==========================================
        // 3. 2 REVERSAL (Mocking previously completed then reversed)
        // ==========================================
        for ($i = 1; $i <= 2; $i++) {
            // Kita gunakan StockService untuk mencatat pergerakan dan me-reverse nya
            $batchId = (string) Str::uuid();
            $movement = $stockService->processMovement(
                $batchId,
                self::class,
                $i,
                'manual_adjustment',
                'bahan_baku',
                $bb1->id,
                'in',
                100,
                "Dummy Initial Stock for Reversal $i",
                $admin->id
            );

            // Now reverse it
            $stockService->reverseMovement($movement, $admin->id, "Salah input kuantitas (Seeder $i)");
        }

        // ==========================================
        // 4. 1 ADJUSTMENT
        // ==========================================
        $stockService->processMovement(
            (string) Str::uuid(),
            self::class,
            999,
            'manual_adjustment',
            'product',
            $product->id,
            'out',
            2,
            AdjustmentType::DAMAGE->value . ': ' . "Barang pecah saat dipindahkan (Seeder)",
            $admin->id
        );

        $this->command->info('DummyTransactionSeeder: Berhasil generate 10 Produksi, 3 Failed, 2 Reversal, dan 1 Adjustment!');
    }
}
